FROM openjdk:8-jre-alpine3.9

RUN apk --update add openjdk7-jre

# copy the packaged jar file into our docker image
COPY quotes.jar /quotes.jar
 
# set the startup command to execute the jar
CMD ["java", "-jar", "/quotes.jar"]
