FROM openjdk:8-jre-alpine3.9

RUN apk --update add openjdk7-jre

ENV STATIC_URL=""
ENV QUOTE_SERVICE_URL=""
ENV NEWSFEED_SERVICE_URL=""
ENV NEWSFEED_SERVICE_TOKEN=T1&eWbYXNWG1w1^YGKDPxAWJ@^et^&kX
# copy the packaged jar file into our docker image
COPY front-end.jar /front-end.jar
 
# set the startup command to execute the jar
CMD ["java", "-jar", "/front-end.jar"]
